### ISSUE TITLE
Adding wifi atheros? 

### ISSUE THREAD

**Issue by alexbanks-git** [avafinger/orangepi-h6-ubuntu-base-minimal#3]
Hi @avafinger,
 Could you try to add the wifi(ar9271)  on the OrangePi H6 please.
I tried to add this module on the official 3.10.65 kernel
when compiling.
in ubuntu it was loaded automatically.
in debian I loaded it manually
insmod (mac80211.ko, ath.ko, ath9k_hw.ko, ath9k_common.ko, ath9k_htc.ko).
in the network interfaces, it was detected, but I could not connect to my wi-fi

**Comment by avafinger** [comment]
I can try but will not be able to test it.
Can you share the .config you used to build those modules?

**Comment by alexbanks-git** [comment]
[configandmodulesandfirmware.zip](https://github.com/avafinger/orangepi-h6-ubuntu-base-minimal/files/3135742/configandmodulesandfirmware.zip)
I'm not good at kernel configuration, I did it for the first time.

**Comment by avafinger** [comment]
@alexbanks-git 

Alex, i have released Mainline Kernel 5.1-rc7 with the ath9k drivers as a module
I had to redo the IMG to be able to fix some issues.

It is a CLI but you can install LXDE and tune the way you like.

* The IMG is here.
https://github.com/avafinger/orangepi-h6-ubuntu-base-minimal/releases/tag/v1.9

You need to install wpa and adjust /etc/network/interfaces to connect to your Wifi AP

Simplest way:
allow-hotplug wlan0
iface wlan0 inet dhcp
	wpa-ssid "AP"
	wpa-psk "PASSWORD"

or install and configure:
wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf


If you have any trouble, please report and check any error with:
dmesg|grep htc
dmesg|grep fail
dmesg|grep err

**Comment by alexbanks-git** [comment]
it's great,thank ,i went to test

**Comment by alexbanks-git** [comment]
I can not write the image on my 8GB microsd sundisk, because 7.38GB is available on it

**Comment by avafinger** [comment]
Looks like you have an SD card with some weird layout.

You can try:
* Try with a new SD CARD
* Write it to a 16 GB, later you adjust partition to free the unused space
* Try with dd on Linux
* Try with Etcher (Linux, maybe Windows)
* Try with win32diskimager

Or try to reformat the SD CARD (from Linux), type:
sudo ./format_sd_mainline /dev/sdX (where X is a letter from b,c,...y)

(SD CARD: /dev/sdX where X is a letter or /dev/mmcblkN where N is your sd card number).

[format_sd_mainline.sh.zip](https://github.com/avafinger/orangepi-h6-ubuntu-base-minimal/files/3140022/format_sd_mainline.sh.zip)

 PS: Make it executable
sudo chmod +x format_sd_mainline.sh

**Comment by avafinger** [comment]
Interesting reading for you:
https://www.raspberrypi.org/forums/viewtopic.php?t=83952

**Comment by alexbanks-git** [comment]
okay I will try

**Comment by alexbanks-git** [comment]
I tried:
1)win32diskimager-RELEASE-0.1-r15-win32
2)resize(gparted) and rewrite
3)clonezilla
4)dd
5)rsync+(dd if=/dev/sdd of=/dev/sdc  bs=446 count=1)
what i got:
turn on the power
the green LED is constantly on and red LED blinking (like heartbeat).
what does it mean?

**Comment by avafinger** [comment]
Please, use win32diskimager  and don't resize on first boot.
Green LED on and RED blinking means the kernel is up. You can try to ssh to the board or ping to see if ethernet is working.

What is your Screen and model? Are you using HDMI?

**Comment by avafinger** [comment]
Forgot to tell, you will not see anything on boot for a few seconds, when the kernel is up it will prompt you with Login screen, if you dont see it after 15 secs, just type in **ubuntu** [ENTER] **ubuntu** [ENTER].

**Comment by alexbanks-git** [comment]
yes i use HDMI on lg tv 47lb671v

**Comment by avafinger** [comment]
Ok. HDMI is fixed on 5.1-rc7 , but CEC is enabled and doesn't know if this is working.
Do you have a debug TTL to USB to check the message on TTL pins?

**Comment by alexbanks-git** [comment]
I not have ttl debag

**Comment by avafinger** [comment]
Do you have ethernet (RJ45) attached? What is your sd card size and maker (brand)?

**Comment by alexbanks-git** [comment]
ethernet attached ,sd card 8gb SanDisk 48MB/s

**Comment by alexbanks-git** [comment]
https://liudr.wordpress.com/2016/03/25/back-up-and-clone-raspberry-pi/

**Comment by alexbanks-git** [comment]
root@linus:~# nmap 192.168.137.2/24
Starting Nmap 7.70 ( https://nmap.org ) at 2019-05-04 13:07 CDT
Illegal character(s) in hostname -- replacing with '*'
Illegal character(s) in hostname -- replacing with '*'
Stats: 0:00:52 elapsed; 251 hosts completed (4 up), 4 undergoing SYN Stealth Scan
SYN Stealth Scan Timing: About 100.00% done; ETC: 13:08 (0:00:00 remaining)
Stats: 0:00:53 elapsed; 251 hosts completed (4 up), 4 undergoing SYN Stealth Scan
SYN Stealth Scan Timing: About 100.00% done; ETC: 13:08 (0:00:00 remaining)
Nmap scan report for D-link.HomeGateway (192.168.137.2)
Host is up (0.020s latency).
Not shown: 996 closed ports
PORT     STATE SERVICE
23/tcp   open  telnet
80/tcp   open  http
5431/tcp open  park-agent
8888/tcp open  sun-answerbook
MAC Address: B8:A3:86:44:C0:64 (D-Link International)

Nmap scan report for OpenWrt (192.168.137.9)
Host is up (0.0022s latency).
All 1000 scanned ports on OpenWrt (192.168.137.9) are closed
MAC Address: D8:E7:43:03:E4:85 (Wush)

Nmap scan report for 192.168.137.56
Host is up (0.0060s latency).
Not shown: 997 filtered ports
PORT    STATE SERVICE
135/tcp open  msrpc
139/tcp open  netbios-ssn
445/tcp open  microsoft-ds
MAC Address: 3C:F8:62:B5:1F:94 (Intel Corporate)

Nmap scan report for 192.168.137.99
Host is up (0.022s latency).
All 1000 scanned ports on 192.168.137.99 are filtered
MAC Address: B4:EF:FA:78:9E:3F (Lemobile Information Technology (Beijing))

Nmap scan report for home-** (192.168.137.5)
Host is up (0.000011s latency).
All 1000 scanned ports on home-** (192.168.137.5) are closed

Nmap done: 256 IP addresses (5 hosts up) scanned in 53.92 seconds
root@linus:~# ssh 192.168.137.9
ssh: connect to host 192.168.137.9 port 22: Connection refused
root@linus:~# ssh ubuntu@192.168.137.9
ssh: connect to host 192.168.137.9 port 22: Connection refused
root@linus:~#

**Comment by alexbanks-git** [comment]
![Screenshot from 2019-05-04 13-11-54](https://user-images.githubusercontent.com/40067057/57183146-51d6cb80-6e6e-11e9-9d49-b0a8246a06cb.png)

**Comment by avafinger** [comment]
why did you try to connect to: ssh ubuntu@192.168.137.9

Should be:

ssh ubuntu@192.168.137.5
or
ssh ubuntu@192.168.137.56

Do you have anything else on your network?

**Comment by alexbanks-git** [comment]
192.168.137.5 this my laptop
192.168.137.99 this my smartphone
192.168.137.56 second laptop
nmap show me:
Nmap scan report for OpenWrt (192.168.137.9)
Host is up (0.0022s latency).
All 1000 scanned ports on OpenWrt (192.168.137.9) are closed
MAC Address: D8:E7:43:03:E4:85 (Wush)
but the web interface in the router does not show this host.

**Comment by avafinger** [comment]
Ok, let's see if this is from the board.
Push the ON/OFF button for ~ 7 secs , it will turn off the board.
Check again if this addr is gone.

**Comment by alexbanks-git** [comment]
that's right, this is some other device

**Comment by avafinger** [comment]
So, my best blind guess is the board booted fine, kernel was up and crashed. Heartbeat would still be working but kernel halted.

The reason? Your SD CARD!

Can you try Etcher?

**Comment by alexbanks-git** [comment]
i try etcher - board does not turn on.
my best blind guess
rootfs partition broken after writing

**Comment by avafinger** [comment]
Sounds like the IMG is broken or the download is corrupt, will check MD5.

**Comment by avafinger** [comment]
You have Linux, i am pushing the Linux way to burn the SD CARD.
Uploading now...

**Comment by alexbanks-git** [comment]
![Новый точечный рисунок](https://user-images.githubusercontent.com/40067057/57184049-182db100-6ebe-11e9-8707-bef0c7eae1f1.jpg)

**Comment by avafinger** [comment]
Please, try this:
https://github.com/avafinger/orangepi-h6-ubuntu-base-minimal/releases/tag/v1.10

**Comment by alexbanks-git** [comment]
ok

**Comment by avafinger** [comment]
Added the missing file: bootloader.bin

**Comment by alexbanks-git** [comment]
it's great!
thank you!
It is working well(green led is on,red led blinking).
Hdmi working fine.
![IMG_20190505_013955-1](https://user-images.githubusercontent.com/40067057/57186314-cdc02a80-6ee5-11e9-8276-b22a9295607b.jpg)

![IMG_20190505_014332-1](https://user-images.githubusercontent.com/40067057/57186321-ed575300-6ee5-11e9-9dff-f3fa7fa4303c.jpg)
![IMG_20190505_015125-1-1](https://user-images.githubusercontent.com/40067057/57186326-f6e0bb00-6ee5-11e9-93cc-70dd8d3ff314.jpg)
![IMG_20190505_014950-1](https://user-images.githubusercontent.com/40067057/57186329-fea05f80-6ee5-11e9-93d3-b144343cd9cb.jpg)

**Comment by alexbanks-git** [comment]
![IMG_20190505_014225-1](https://user-images.githubusercontent.com/40067057/57186396-0f050a00-6ee7-11e9-9ec7-a1e95baafdcc.jpg)

**Comment by alexbanks-git** [comment]
![IMG_20190505_014225-1-1-1](https://user-images.githubusercontent.com/40067057/57186415-71f6a100-6ee7-11e9-97ab-65d4dd435461.jpg)

**Comment by avafinger** [comment]
Good, and how about the ath9k?

**Comment by alexbanks-git** [comment]
![IMG_20190505_115658-1-1-1](https://user-images.githubusercontent.com/40067057/57191363-4a2a2c00-6f2d-11e9-8bca-c9b3356cb3ed.jpg)
here I:
Disconnected the lan cable,disconnected the keyboard and connected ar9271.
Then disconnected the ar9271 and reconnected the keyboard and typed dmesg.


on ethernet:
ipv6 default on

,not working inet connection ,
no connect ssh

**Comment by alexbanks-git** [comment]
Typed this:
net.ipv6.conf.all.disable_ipv6 = 1 
net.ipv6.conf.default.disable_ipv6 = 1 
net.ipv6.conf.lo.disable_ipv6 = 1.
Lan not working (leds off)after reboot.

**Comment by alexbanks-git** [comment]
![IMG_20190505_125121-1-1-1](https://user-images.githubusercontent.com/40067057/57192072-28cd3e00-6f35-11e9-8166-06a22eece95e.jpg)

**Comment by avafinger** [comment]
There is an adjustment that possibly fixes this issue.

You can try to adjust emac **rx-delay** and **tx-delay**, which is in /boot/opi-h6.dtb (DT).
The actual vaues are 200, start with 0 and then increment by 100.

Start with rx (rx-delay must be a multiple of 100 i.e 100,200,300...) and see if can get an IP at some point.
Every time you change the value for a new one you must shut down and power cycle the board and see if has improved.

Check what file you should edit (**opi-h6.dtb is a symlink to a file, do not edit this symlink, edit the file it points to**):
```
cd /boot
ls -la opi-h6.dtb
```
Decompile the file (not the symlink) DTB with DTC (i am not sure dtc is already installed):
For example:
**sudo dtc -I dtb -o opi.dts opi-h6.dtb_5.1.0-rc7-h6**

Edit the file **opi.dts(( and change the value, save and compile to DTB again. Boot and check if improved.

Find the string:
ethernet@5020000 {
compatible = "allwinner,sun50i-h6-emac", "allwinner,sun50i-a64-emac";
syscon = <0x1f>;
reg = <0x5020000 0x10000>;
interrupts = <0x0 0xc 0x4>;
interrupt-names = "macirq";
resets = <0x2 0x21>;
reset-names = "stmmaceth";
clocks = <0x2 0x54>;
clock-names = "stmmaceth";
status = "okay";
#address-cells = <0x1>;
#size-cells = <0x0>;
pinctrl-names = "default";
pinctrl-0 = <0x20>;
phy-mode = "rgmii";
phy-handle = <0x21>;
phy-supply = <0x22>;
**allwinner,rx-delay-ps = <0x0>;**
**allwinner,tx-delay-ps = <0x0>;**

re-compile with:
**sudo dtc -I dts -o opi-h6.dtb_5.1.0-rc7-h6.dts**

Please, when providing info doo this:
dmesg|grep eth > eth_message.txt and attach the file.

And check your RJ45 connection to the board!

**Comment by avafinger** [comment]
You can do it in your HOST PC (linux), no need to do it on the board.

**Comment by alexbanks-git** [comment]
[eth_message.txt](https://github.com/avafinger/orangepi-h6-ubuntu-base-minimal/files/3145682/eth_message.txt)
ethernet working

**Comment by avafinger** [comment]
And the athk9?

**Comment by alexbanks-git** [comment]
no 
[dmesg_iw_dev_lsmod.txt](https://github.com/avafinger/orangepi-h6-ubuntu-base-minimal/files/3147045/dmesg_iw_dev_lsmod.txt)

**Comment by avafinger** [comment]
Looks like the entire wifi stack is needed or some module support is missing. As soon as a new kernel is released i will build with all modules.
See if you can find the Product ID (install packages if necessary)
`lsusb -v`

and
`dmesg|grep htc`

**Comment by avafinger** [comment]
dmesg|grep usb

**Comment by avafinger** [comment]
try also:

`lsusb -v | grep -E '\<(Bus|iProduct|bDeviceClass|bDeviceProtocol)' 2>/dev/null > usb.txt`

**Comment by alexbanks-git** [comment]
[lsusb_dmesg.txt](https://github.com/avafinger/orangepi-h6-ubuntu-base-minimal/files/3148439/lsusb_dmesg.txt)
[usb.txt](https://github.com/avafinger/orangepi-h6-ubuntu-base-minimal/files/3148440/usb.txt)

**Comment by avafinger** [comment]
What do you see if:
sudo modprobe ath9k

**Comment by alexbanks-git** [comment]
root@opi-h6:~# modprobe ath9k
modprobe: FATAL: Module ath9k not found in directory /lib/modules/5.1.0-rc7
root@opi-h6:~# 


![Screenshot_20190506-190321-1](https://user-images.githubusercontent.com/40067057/57238427-108f1900-7032-11e9-800d-d4f70a351035.jpg)

**Comment by avafinger** [comment]
Please, check if i made a mistake and forgot to build the driver:
`
sudo cat /proc/config.gz | gunzip > running.config`

Edit the file running.config and search for the ATH9K.

**Comment by avafinger** [comment]
cat running.config|grep ATH9

**Comment by alexbanks-git** [comment]
![Screenshot_20190506-200937-1](https://user-images.githubusercontent.com/40067057/57242023-1c330d80-703b-11e9-896a-31129a9b732a.jpg)

**Comment by avafinger** [comment]
Mainline Kernel 5.1.0 has been released!

See:
https://github.com/avafinger/orangepi-h6-ubuntu-base-minimal/releases/tag/v1.11

```
ubuntu@opi-h6:~$ sudo modprobe ath9k
[sudo] password for ubuntu: 
ubuntu@opi-h6:~$ lsmod
Module                  Size  Used by
ath9k                  86016  0
ath9k_common           16384  1 ath9k
ath9k_hw              417792  2 ath9k_common,ath9k
ath                    32768  3 ath9k_common,ath9k,ath9k_hw
mac80211              385024  1 ath9k
cfg80211              282624  4 ath9k_common,ath9k,ath,mac80211
rfkill                 24576  2 cfg80211
fuse                   98304  3
snd_soc_hdmi_codec     16384  1
dw_hdmi_i2s_audio      16384  0
dw_hdmi_cec            16384  0
crct10dif_ce           16384  1
snd_soc_simple_card    20480  0
snd_soc_spdif_tx       16384  1
snd_soc_simple_card_utils    16384  1 snd_soc_simple_card
sun8i_drm_hdmi         24576  0
dw_hdmi                28672  2 sun8i_drm_hdmi,dw_hdmi_i2s_audio
cec                    49152  3 sun8i_drm_hdmi,dw_hdmi_cec,dw_hdmi
sunxi_cir              16384  0
rc_core                32768  2 sunxi_cir
sunxi_cedrus           32768  0
videobuf2_dma_contig    20480  1 sunxi_cedrus
videobuf2_memops       16384  1 videobuf2_dma_contig
v4l2_mem2mem           20480  1 sunxi_cedrus
videobuf2_v4l2         24576  2 sunxi_cedrus,v4l2_mem2mem
videobuf2_common       49152  3 sunxi_cedrus,videobuf2_v4l2,v4l2_mem2mem
videodev              192512  4 sunxi_cedrus,videobuf2_v4l2,videobuf2_common,v4l2_mem2mem
sun4i_drm              20480  2
sun4i_frontend         16384  1 sun4i_drm
sun4i_tcon             28672  1 sun4i_drm
media                  32768  5 sunxi_cedrus,videodev,videobuf2_v4l2,videobuf2_common,v4l2_mem2mem
sun8i_tcon_top         16384  4 sun8i_drm_hdmi,sun4i_tcon,sun4i_drm
sun8i_mixer            40960  0
ip_tables              32768  0
x_tables               28672  1 ip_tables
ipv6                  360448  38
ubuntu@opi-h6:~$ uname -ra
Linux opi-h6 5.1.0 #1 SMP PREEMPT Mon May 6 11:36:09 -03 2019 aarch64 aarch64 aarch64 GNU/Linux

```

**Comment by alexbanks-git** [comment]
Yes!nice work!
You are wizard!
Thank you!
![Screenshot_20190506-225657-1](https://user-images.githubusercontent.com/40067057/57251422-6b386d00-7052-11e9-9ef8-e146774da135.jpg)
![Screenshot_20190506-230027-1](https://user-images.githubusercontent.com/40067057/57251591-dd10b680-7052-11e9-9086-322ae1f0bf28.jpg)

**Comment by avafinger** [comment]
Assuming is OK!
