### ISSUE TITLE
I want to know if 100Mbps and 1Gbps port can used at same time?

### ISSUE THREAD

**Issue by be-engineer** [avafinger/orangepi-h6-ubuntu-base-minimal#8]
Our H6 board use DDR3 sdram, not LPDDR3.So this image can not run on my board. Could you provide the source code of your uboot，I can recompile it for my board.

**Comment by be-engineer** [comment]
Another question is, are these two network interfaces an internal EPHY and an external PHY? Or is one of the USB-converted network interfaces?

**Comment by avafinger** [comment]
https://github.com/u-boot/u-boot/archive/v2019.10.tar.gz, i think there was a patch applied for the reboot issue which was still around with the newer u-boot. You should go with the latest u-boot.

No USB-converted network interface. 100 Mbps/1Gbps at the same time

**Comment by be-engineer** [comment]
> https://github.com/u-boot/u-boot/archive/v2019.10.tar.gz, i think there was a patch applied for the reboot issue which was still around with the newer u-boot. You should go with the latest u-boot.
> 
> No USB-converted network interface. 100 Mbps/1Gbps at the same time
 Thank you very much.
